
import __ASTRO_IMAGE_IMPORT_Zd92Xd from "../../assets/libra1.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Flibra.md";
import __ASTRO_IMAGE_IMPORT_iSlmc from "../../assets/libra2.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Flibra.md";
import __ASTRO_IMAGE_IMPORT_OUJGB from "../../assets/libra3.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Flibra.md";
import __ASTRO_IMAGE_IMPORT_Z1WSr2z from "../../assets/Toros.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Ftoros.md";
import __ASTRO_IMAGE_IMPORT_1vlSnF from "../../assets/pegasus1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fpegasus.md";
import __ASTRO_IMAGE_IMPORT_2wXOiz from "../../assets/pegasus2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fpegasus.md";
import __ASTRO_IMAGE_IMPORT_Z1vAnAs from "../../assets/pegasus3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fpegasus.md";
export default new Map([["../../assets/libra1.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Flibra.md", __ASTRO_IMAGE_IMPORT_Zd92Xd], ["../../assets/libra2.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Flibra.md", __ASTRO_IMAGE_IMPORT_iSlmc], ["../../assets/libra3.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Flibra.md", __ASTRO_IMAGE_IMPORT_OUJGB], ["../../assets/Toros.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Ftoros.md", __ASTRO_IMAGE_IMPORT_Z1WSr2z], ["../../assets/pegasus1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fpegasus.md", __ASTRO_IMAGE_IMPORT_1vlSnF], ["../../assets/pegasus2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fpegasus.md", __ASTRO_IMAGE_IMPORT_2wXOiz], ["../../assets/pegasus3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fpegasus.md", __ASTRO_IMAGE_IMPORT_Z1vAnAs]]);
		